### ISSUE TITLE
couple of typos noticed in notebook 02

### ISSUE THREAD

**Issue by jgd10** [rsokl/testing-tutorial#4]
I noticed a couple of small typos in notebook 02 whilst taking this course.

Both are in cell No. 4

i) "Rountrip Pairs" -> "Roundtrip Pairs"

ii) immediately after this there is a code snippet that is missing the `python` tag in markdown

**Comment by jgd10** [comment]
Just noticed i) is fixed by #3 but not ii) I think

**Comment by Zac-HD** [comment]
Fixed in aafe078355a6e06c2728ac717220ff3a8c5d571c 😁
