### ISSUE TITLE
Incorrect import in paragraph 'Manual Tests' of 00_Taxonomy_of_Testing_STUDENT.ipynb?

### ISSUE THREAD

**Issue by ronaldborman** [rsokl/testing-tutorial#5]
Apologies in advance if I got this wrong, because I'm relatively new to Python. I'm watching the PyCon 2022 Hypothesis session and trying the examples.

I followed the instructions in README.md (cloning the repo and then `pip install -e .` in the root of the project), but when I add the test in paragraph 'Manual Tests' of 00_Taxonomy_of_Testing_STUDENT.ipynb and then run pytest, I get an `ImportError: cannot import name 'count_vowels' from 'pbt_tutorial'`.

When I change the import statement to `from pbt_tutorial.basic_functions import count_vowels` (using packagename.modulename), it works.

BTW, I also managed to get it working when I add `from . basic_functions import *` to `__init__.py` of the package. The README.md mentioned something about adding a function definition to `__init__.py`, but would adding the definition itself not lead to repetition?

**Comment by rsokl** [comment]
Thanks for posting this! This has been fixed in the notebooks.
